function importCSVs()
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 21-Jun-2012 10:28:24

csvFiles = dir('*.csv'); 
numfiles = length(csvFiles);
mydata = cell(1, numfiles);


for k = 1:numfiles
  mydata{k} = importdata(csvFiles(k).name);
  varname = csvFiles(k).name;
  d48 = mydata{1}.textdata(:,[18 3:11 13:16]);
  d47 = mydata{1}.textdata(:,[35 20:28 30:33]);
  d46 = mydata{1}.textdata(:,[52 37:45 47:50]);
  
  devID = size(d48);
  vecDevID = ones(d48,1);
  
  d482 = [48*vecDevID d48];
  d472 = [47*vecDevID d47];
  d462 = [46*vecDevID d46];
  
  data = [d462; d472; d482];
  
  assignin('base',varname, data);
end
