function importCSVs()
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 21-Jun-2012 10:28:24

csvFiles = dir('*.csv'); 
numfiles = length(csvFiles);
mydata = cell(numfiles,1);
% varN = '';

for k = 1:numfiles
  mydata{k,1} = importdata(csvFiles(k).name);
  
  aa = char(csvFiles(k).name);
  
  if strfind(aa,'Ankle')
      if strfind(aa,'Right')
          varN = strcat('AFER',aa(2:5));
      
      else
          varN = strcat('AFEL',aa(2:5));
      end
  
  else
    if strfind(aa,'Knee')
      if strfind(aa,'Right')
          varN = strcat('KFRR' ,aa(2:5));
      
      else
          varN = strcat('KFLL', aa(2:5));
      end
  
    else
        if strfind(aa,'Hip')
            if strfind(aa,'Extension')
                if strfind(aa,'Right')
                    varN = strcat('HERR', aa(2:5));
                else
                    varN = strcat('HELL', aa(2:5));
                end
            else
                if strfind(aa,'Abduction')
                    if strfind(aa,'Right')
                        varN = strcat('HAAR', aa(2:5));
                    else
                        varN = strcat('HAAL', aa(2:5));
                    end
                else 
                    if strfind(aa,'Flexion')
                        if strfind(aa,'Right')
                            varN = strcat('HFRR', aa(2:5));
                        else
                            varN = strcat('HFLL', aa(2:5));
                        end
                    else
                        if strfind(aa,'Right')
                            varN = strcat('EHRR', aa(2:5));
                        else
                            varN = strcat('EHRL', aa(2:5));
                        end
                    end
                end
            end
        end
    end
  end
  
  varname = genvarname(varN);
  ddd = mydata{k,1}.textdata;
  sY = size(ddd,1);
  d48 = [ddd(1:sY,18) ddd(1:sY, 13:16)];
  d47 = [ddd(1:sY,35) ddd(1:sY, 30:33)];
  d46 = [ddd(1:sY,52) ddd(1:sY, 47:50)];
  
  vec48 = num2cell(48*ones(size(d48,1) ,1));
  vec47 = num2cell(47*ones(size(d47,1),1));
  vec46 = num2cell(46*ones(size(d46,1),1));
  
  d482 = [vec48 d48];
  d472 = [vec47 d47];
  d462 = [vec46 d46];
  
  data = [d462 d472 d482];
  
  assignin('base',varname, data);
end
